### ISSUE TITLE
Issue with deploying GoAlert on EKS

### ISSUE THREAD

**Issue by delpic** [target/goalert#29]
I've been having an issue with setting up the service for GoAlert on our Kubernetes cluster running on EKS. The actual deployment manifest deploys fine, as well as the service manifest. The exact issue I am having is that once I deploy the service manifest and it creates an ELB, after awhile the instances show out of service as the health checks fail trying to reach port 8081. Yet if I run a `kubectl port-forward` using port 8081, I am able to reach the gui on http://localhost:8081 with no problem from my workstation. The other odd thing is that I was able to access a bash shell on a pod within the cluster and run a curl against the GoAlert pod. I was getting `connection refused` messages.

Not sure if you have encountered anything similar when deploying to k8s. Here are my manifests:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kalert
  namespace: alert
  labels:
    app: kalert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kalert
  template:
    metadata:
      labels:
        app: kalert
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/role
                operator: NotIn
                values:
                - XXXXX
      containers:
      - image: goalert/goalert
        imagePullPolicy: Always
        name: kalert
        command: ["/bin/sh"]
        args: ["-c", "goalert --db-url postgres://XXXXXXXXXXXXX"]
        ports:
        - containerPort: 8081
          protocol: TCP
```
```
apiVersion: v1
kind: Service
metadata:
  name: kalert-gui
  namespace: alert
spec:
  selector:
    app: kalert
  ports:
  - name: kalert
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: LoadBalancer
```
```
kubectl describe service kalert-gui --namespace=alert
Name:                     kalert-gui
Namespace:                alert
Labels:                   <none>
Annotations:              <none>
Selector:                 app=kalert
Type:                     LoadBalancer
IP:                       10.100.232.57
LoadBalancer Ingress:     XXXXXXXXXXXXXXXXX.us-east-1.elb.amazonaws.com
Port:                     kalert  8081/TCP
TargetPort:               8081/TCP
NodePort:                 kalert  32369/TCP
Endpoints:                172.24.2.202:8081
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                Age   From                Message
  ----    ------                ----  ----                -------
  Normal  EnsuringLoadBalancer  2m2s  service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   119s  service-controller  Ensured load balancer
```
```
kubectl get pods --output=wide --namespace=alert
NAME                      READY   STATUS    RESTARTS   AGE   IP             NODE                          NOMINATED NODE
kalert-56bb45cc78-zzq7f   1/1     Running   0          74m   172.24.2.202   ip-172-24-2-15.ec2.internal   <none>
```

Thanks!
