### ISSUE TITLE
Adding A slack notification or trigger does not work

### ISSUE THREAD

**Issue by jupeeter8** [target/goalert#4172]
Bug:
When adding notification rule for a schedule or escalation policy the UI shows  "unexpected error": Logs Mention missing scope

Logs:
```AuthUserID=387cc228-ace3-4a10-b61a-226e513e6359 RequestID=7dcf0686-aab8-472c-a6e4-5cd73fdb425a error="input: setScheduleOnCallNotificationRules missing_scope" host=<host_address> http_method=POST http_proto=HTTP/1.1 referer="<host_address>/schedules/0c98347c-19b3-4973-910d-3bc320eb8b78/on-call-notifications" remote_addr="127.0.0.1:43340" uri=/api/graphql x_forwarded_for=<client_ip> x_forwarded_host=```

![image](https://github.com/user-attachments/assets/fbacdc75-74ee-4a00-bf4d-e00d481d0792)

Scopes For the bot
![image](https://github.com/user-attachments/assets/46462872-101e-499f-8ddd-89dea2b084b8)

Slack credentials are correctly configured

This is how goalert was setup
I have an VM where go alert is already running.
1. Took a database dump of the existing go alert
2. Created a new DB and restored the dump to it  
3. Started another instance of go alert on a new VM with the new DB
4. Created a new Slack Bot
5. Updated the slack configs in the go alert tool

**Comment by mastercactapus** [comment]
Have you tried using the manifest YAML to configure the application in Slack?
![image](https://github.com/user-attachments/assets/d1e86ade-c910-4aea-963e-82d61840551c)


Here's the current list of scopes in that template:
```
oauth_config:
  scopes:
    bot:
      - links:read
      - chat:write
      - channels:read
      - groups:read
      - im:read
      - im:write
      - users:read
      - users:read.email
      - usergroups:read
      - usergroups:write
      - team:read
```
